import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col gap-2 justify-center items-center w-screen h-screen overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
